name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # Display full year instead of half year
          plugin_languages: yes
          plugin_lines: yes
          plugin_repositories: yes
          plugin_repositories_featured: virtual-cast/babylon-vrm-loader, il-m-yamagishi/bleeding
          plugin_topics: yes
          plugin_topics_sort: stars    # Sort by most starred topics
